### ISSUE TITLE
Configure your own websocket location?

### ISSUE THREAD

**Issue by poVoq** [KiwiChat/KiwiChat#1]
KiwiIRC supports direct websocket connections to IRC servers like ergo.chat, would be nice if it was possible to configure that.

**Comment by KiwiChat** [comment]
Go to [https://custom.kiwichat.ml/](https://custom.kiwichat.ml/) create your amazing KiwiChat based plugin, supports direct websocket connections to IRC servers
Configure your settings, simply download and it into your plugins folder. Configure your settings in the WordPress dashboard then drop the short tag: **[customkiwichat]** into your page or post. Instantly your users will be able to stay connected via IRC.
